# Generated by Django 5.2.5 on 2025-09-29 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='sluglink',
        ),
    ]
