# Generated by Django 5.2.5 on 2025-10-03 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_slug_product_sluglink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quantitys',
        ),
    ]
